# Leaf {#cha:leaf}


```{r leaf-setup, message=FALSE, warning=FALSE, echo=FALSE}
source('_setup.R')
```

The apex model is developed to simulate leaf dynamic based on leaf cohort model.






<!-- 

## Cohort population

Cohort population is initialized as the total stem population at appearance of leaf cohort, and proportionally reduced by plant and stem mortalities (\@ref(#sec-structure-mortality)) at each day after appearance.

<div class='fig-output'>
```{r live-population}
# y_cols <- c('Wheat.Leaf.CohortLivePopulation')
# plot_report_vector(report, x_var, y_cols, x_lab = x_lab, y_lab = 'Live (cohort) population')

```
</div>

The total leaf number is multiplied by leaf cohort number and stem number (Figure \@ref(fig:leaf-number)).

<div class="fig-output">
```{r leaf-number, fig.asp = 1.3, fig.cap='Appeared number of green, senesced and total leaves'}
y_cols <- c(
    'Wheat.Leaf.PlantAppearedLeafNo',
    #'Wheat.Leaf.PlantAppearedGreenLeafNo',
    'Wheat.Leaf.PlantsenescedLeafNo')

plot_report(report, x_var, y_cols, x_lab = x_lab, 
            y_lab = 'Leaf number')
```
</div>



```{block, type='rmdimportant', echo=TRUE}
The tiller death is detached from plants, but leaf death isn't detached.
```



-->





